//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.04 at 02:25:15 PM MSK 
//


package com.epam.shop.entity;


public class OnlineShop {

    protected Products products;
    protected Users users;

    public OnlineShop() {
        products = new Products();
        users = new Users();
    }

    /**
     * Gets the value of the products property.
     *
     * @return
     *     possible object is
     *     {@link Products }
     *
     */
    public Products getProducts() {
        return products;
    }

    /**
     * Sets the value of the products property.
     *
     * @param value
     *     allowed object is
     *     {@link Products }
     *
     */
    public void setProducts(Products value) {
        this.products = value;
    }

    /**
     * Gets the value of the users property.
     *
     * @return
     *     possible object is
     *     {@link Users }
     *
     */
    public Users getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     *
     * @param value
     *     allowed object is
     *     {@link Users }
     *     
     */
    public void setUsers(Users value) {
        this.users = value;
    }

}
