//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.04 at 02:25:15 PM MSK 
//


package com.epam.shop.entity;


import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class Products {

    protected List<Product> product;

    public Products() {
        product = new ArrayList<>();
    }

    public void setProduct(List<Product> product) {
        this.product = product;
    }

    public List<Product> getProduct() {
        return this.product;
    }

    /**
     * Setter for product
     * @param prod product whith needed to add at the list
     */
    public void addProduct(Product prod) {
        product.add(prod);
    }

    /**
     * This method check available product
     * @param name product name
     * @return list of product which have such name
     */
    public Optional<Product> getProducto(String name){
        return product.stream()
                .filter(p->name.equals(p.getName()))
                .findFirst();
    }

}
